### PR TITLE
Add template inheritance

### PR DESCRIPTION
**Pull request by Alir3za97**
Create base.html file in order to extending other templates from it.
Change all template and use inheritance in them.

### CODE REVIEW

**Review by arf1372 — COMMENTED** [review]
This is a better idea to split base.html into:
- base.html
- navbar.html
- head.html

and then create a file named `template.html` and use that. This is more modular.

**Comment by mahyarap** [comment]
@arf1372 I'm strongly against your idea of that much separation. You wouldn't call that modularization, it's just simply over-engineering! Simple is better than complex! Try to keep it [KISS](https://en.wikipedia.org/wiki/KISS_principle)ing :)

**Comment by Alir3za97** [comment]
What can we do about footer?, why it's in same block with other elements of content?

**Comment by arf1372** [comment]
@mahyarap may be! I've helped myself to do so. And I like the zen of python! :)

**Comment by mahyarap** [comment]
@Alir3za97 Just keep the footer in `base.html`. I think 90% of our templates will use `base.html`. In a rare situation, if we needed not to include the footer, we could just introduce another base template, something like `bare_base.html` without the footer.

**Comment by arf1372** [comment]
@Alir3za97 I cannot get your point.  
Can you explain more and make examples?

**Comment by arf1372** [comment]
@mahyarap The `bare_base.html` thing that you said is just a specific model of me! :|

**Comment by mahyarap** [comment]
@arf1372 I said "in a **rare** situation", and for the moment we can stick to our current simple model. If the need arose, then we can make it more complex.

**Review by mahyarap — COMMENTED** [review]
- I suggest putting the footer in `base.html`
- I think 90 percent of the time, we need the navbar. It'd be better if you don't make it a block.

**Comment by arf1372** [comment]
@mahyarap I think having `navbar` and `head` section as blocks may be better thing. I'll clone @Alir3za97 's repo and make my changes to it then re-ask reviews.

Also the structure of this template is enough I think. would you mind approve this one @mahyarap ?

**Comment by mahyarap** [comment]
@arf1372 Let @Alir3za97 finish the job. It's his own pull request after all ;)

**Comment by arf1372** [comment]
@mahyarap O-KAY! :)  
@Alir3za97 Hurry up! ')

@mahyarap So who's responsible for approving this PR? @Alir3za97 himself or repo moderators?

**Comment by Alir3za97** [comment]
@mahyarap

**Comment by mahyarap** [comment]
@arf1372 Currently you and me have write access and we have an ad-hoc maintainer. Since Alireza himself has done this issue, it doesn't really make sense to merge it himself so it's up to us now.

**Review by mahyarap — APPROVED** [review]
I know that navbar block thing's gonna be a pain in the neck but I merge it anyway

**Pull request merged**
